version: 1
labels:
  - label: "automerge"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/plugins.sbt"
      - "project/build.properties"
      - "project/Dependencies.scala"
      - "examples/src/main/scala/.*\\.scala"
      - "model_update_scripts/.*\\.scala"
      - "\\.scalafmt\\.conf"
  - label: "dependency"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/plugins.sbt"
      - "project/build.properties"
      - "project/Dependencies.scala"
      - "examples/src/main/scala/.*\\.scala"
      - "model_update_scripts/.*\\.scala"
      - "\\.scalafmt\\.conf"
